### PR TITLE
Fixing a misspelling

### PR DESCRIPTION
**Pull request by Timed-kitty-cat**
It's not "I am now a developer and I loved programming in \*insert programming language name here\*" it's "I am now a developer and I love programming in \*insert programming language name here\*" or "I am now a developer who loves programming in \*insert programming language name here\*"

### CODE REVIEW

**Comment by TheColaber** [comment]
Dude, can you actually like learn to code and stop making useless PRs?

**Comment by Timed-kitty-cat** [comment]
@TheColaber my PRs are useful and I know a little coding (just LOLCODE)

**Comment by TheColaber** [comment]
@Timed-kitty-cat Please hear this advice. You are ruining your reputation with PRs that are useless. You may think they are useful, but useful prs actually contribute to something cool. I would recommend waiting until you are old enough to be on GitHub so you'll understand and start fresh. Changing your username ever so often doesn't change anything. Please listen to this advice. The more places you get banned from, the more this will haunt you in your future.

**Comment by Timed-kitty-cat** [comment]
@TheColaber "the more this will haunt you in your future" Impossible.

**Comment by TheColaber** [comment]
Hey, at least we tried. All we have left is the report button.

**Comment by Timed-kitty-cat** [comment]
@TheColaber I'm 13 and don't report me

**Comment by CluckCluckChicken** [comment]
I really think you should stop. According to [this](https://github.com/jeffalo/ocular/issues/58#issue-871486903), your Scratch username is "Ilikesonic100". On your Scratch profile. it says you are a 3rd grader. I don't know any 3rd graders who are 13. You've already been IP banned on Scratch, blocked on many GitHub repos, had almost all of your PRs closed, and gotten a bad reputation. I think you should stop now before you get banned from GitHub for being underage, and then when your old enough and can actually code things that aren't glaringly obviously copied from one of those websites with a really generic domain name, weird styling and English that looks like something GitHub Copilot typed. Your PRs seem to almost always "resolve nothing" contain either "clarity fixed" which usually just make things more inconsistent and confusing, "spelling fixes" which don't fix any spelling at all (such as [this PR,](https://github.com/SheepTester/sheeptester.github.io/pull/26) if something isn't written in your language, don't request for it to be changed, that's like making a PR in a repo written entirely in French, to change it to English), or just useless things. It's very annoying, and you are just going to regret it in the future. Again, please stop now before you get perma-banned (once your banned there isn't much you can do), so that in 5 years or so you can come back and actually write real code.

**Comment by Timed-kitty-cat** [comment]
@CluckCluckChicken I'm 13 and held back in 3rd grade

**Comment by CluckCluckChicken** [comment]
> @CluckCluckChicken I'm 13 and held back in 3rd grade

Are you expecting me to believe that or something? You also aren't acting like a 13 year old, and you made a PR in one of GitHub's official repos to allow 9 year olds to use GitHub.

**Comment by Timed-kitty-cat** [comment]
@CluckCluckChicken the PR was so any other people who are 9 can use GitHub

**Comment by Timed-kitty-cat** [comment]
> You also aren't acting like a 13 year old

yes I am

**Comment by CluckCluckChicken** [comment]
😳😱😱😂time cat exposed❔❔(100% NOT FAKE) (REAL LEGIT 2021)😳😳😂

**Comment by Timed-kitty-cat** [comment]
> 😳😱😱😂time cat exposed❔❔(100% NOT FAKE) (REAL LEGIT 2021)😳😳😂

ah yes clickbait involving me, the TIMED Cat, not Time Cat.

**Comment by CluckCluckChicken** [comment]
> > 😳😱😱😂time cat exposed❔❔(100% NOT FAKE) (REAL LEGIT 2021)😳😳😂
> 
> ah yes clickbait involving me, the TIMED Cat, not Time Cat.

clock mammal

**Comment by Timed-kitty-cat** [comment]
> > > 😳😱😱😂time cat exposed❔❔(100% NOT FAKE) (REAL LEGIT 2021)😳😳😂
> > 
> > 
> > ah yes clickbait involving me, the TIMED Cat, not Time Cat.
> 
> clock mammal

Tick-tock Dog

**Comment by Timed-kitty-cat** [comment]
> can actually code things that aren't glaringly obviously copied from one of those websites with a really generic domain name

Bruh I take my code from replit

**Comment by TheColaber** [comment]
> > You also aren't acting like a 13 year old
> 
> yes I am

Please prove in one or more sentences how all your past actions make you a 13-year-old. 
Hint: You are going to need more than 1.
```
https://github.com/LLK/scratch-gui/pull/7069
https://github.com/LLK/scratchjr/pull/415
https://github.com/scratchblocks/scratchblocks/pull/359
https://github.com/ScratchAddons/ScratchAddons/pull/2630
https://github.com/TurboWarp/scratch-gui/pull/218
https://github.com/ScratchAddons/ScratchAddons/pull/2696
https://github.com/ScratchAddons/ScratchAddons/pull/2702/files
https://github.com/LLK/scratch-gui/pull/7230/files
https://github.com/github/docs/pull/7286 < wow, even gh smh
https://github.com/github/docs/pull/7288 < again, come on
https://github.com/curl/curl/pull/7282 < oh, great... curl
https://github.com/github/docs/pull/7791/files < man you are really pushing to stay on gh
https://github.com/github/docs/pull/7792/files < hey they closed it, guess you better delete your account

and many more examples...
```

**Comment by TheColaber** [comment]
Also, realize that this is not only a "not allowed thing" but also a legal thing
image

**Comment by CluckCluckChicken** [comment]
as well as the above, you will inevitably be banned sooner or later and if it's permanent then there isn't really much you can do but ban evade, which isn't allowed. in a few years time when you want to actually do programming you'll go to github and remember that you got permanently banned 5 years ago.

**Comment by Timed-kitty-cat** [comment]
> as well as the above, you will inevitably be banned sooner or later and if it's permanent then there isn't really much you can do but ban evade, which isn't allowed. in a few years time when you want to actually do programming you'll go to github and remember that you got permanently banned 5 years ago.

no. they dont ban people

**Comment by Timed-kitty-cat** [comment]
> guess you better delete your account

I am owner of multiple organizations so no

**Comment by CluckCluckChicken** [comment]
> > as well as the above, you will inevitably be banned sooner or later and if it's permanent then there isn't really much you can do but ban evade, which isn't allowed. in a few years time when you want to actually do programming you'll go to github and remember that you got permanently banned 5 years ago.
> 
> no. they dont ban people

yes, they do. if you break tos and they find out then they will ban your account.

> > guess you better delete your account
> 
> I am owner of multiple organizations so no

organizations with nobody in them that no-one really cares about

**Comment by Timed-kitty-cat** [comment]
> Please prove in one or more sentences how all your past actions make you a 13-year-old.

Okay. First, I use good grammar and spelling, and my words are never nonsense. My PRs are useful but nobody understands them, saying they're useless. It is also disrespectful to block people from your organization because they made a useless PR. Anyways, get out of this TED Talk.

**Comment by CluckCluckChicken** [comment]
> > Please prove in one or more sentences how all your past actions make you a 13-year-old.
> 
> Okay. First, I use good grammar and spelling, and my words are never nonsense. My PRs are useful but nobody understands them, saying they're useless. It is also disrespectful to block people from your organization because they made a useless PR. Anyways, get out of this TED Talk.

if everyone thinks your pr is bad then your pr is bad. it isn't disrespectful to block someone if they're being spammy. it's disrespectful to post a pr on github docs called "tell the truth" and have it say "if you are under 13, we want to discourage you from learning to code".

**Comment by Timed-kitty-cat** [comment]
> it isn't disrespectful to block someone if they're being spammy. it's disrespectful to post a pr on github docs called "tell the truth" and have it say "if you are under 13, we want to discourage you from learning to code".

It's the opposite way around.

**Comment by CluckCluckChicken** [comment]
> > it isn't disrespectful to block someone if they're being spammy. it's disrespectful to post a pr on github docs called "tell the truth" and have it say "if you are under 13, we want to discourage you from learning to code".
> 
> It's the opposite way around.

no sorry but it's not



> > Please prove in one or more sentences how all your past actions make you a 13-year-old.
> 
> Okay. First, I use good grammar and spelling, and my words are never nonsense. My PRs are useful but nobody understands them, saying they're useless. It is also disrespectful to block people from your organization because they made a useless PR. Anyways, get out of this TED Talk.

you made a site with some random garbage on it, with a link to "your new site", your new site being exactly the same as your old site but with the text replaced to say

Solid Pancake
It tastes like stone. Gross!
Solid Pancake
Solid pancakes are stone discs dyed to look like pancakes. Yummy Yucky.

**Comment by Timed-kitty-cat** [comment]
> you made a site with some random garbage on it, with a link to "your new site", your new site being exactly the same as your old site but with the text replaced to say
> 
> Solid Pancake
> It tastes like stone. Gross!
> Solid Pancake
> Solid pancakes are stone discs dyed to look like pancakes. Yummy Yucky.

That was a joke based on my solid-pancake repo.

**Comment by CluckCluckChicken** [comment]
> > you made a site with some random garbage on it, with a link to "your new site", your new site being exactly the same as your old site but with the text replaced to say
> > Solid Pancake
> > It tastes like stone. Gross!
> > Solid Pancake
> > Solid pancakes are stone discs dyed to look like pancakes. Yummy Yucky.
> 
> That was a joke based on my solid-pancake repo.

but it wasnt funny and why do you have a repo called that in the first place? the point is we know that you're 8 or 9 and you're too young to use github so please just stop before you get banned.

**Comment by Timed-kitty-cat** [comment]
> the point is we know that you're 8 or 9 and you're too young to use github so please just stop before you get banned.

Bro I live in Dream Land and the Ability Academy 3rd Grade is for 13 year olds

**Comment by CluckCluckChicken** [comment]
> > the point is we know that you're 8 or 9 and you're too young to use github so please just stop before you get banned.
> 
> Bro I live in Dream Land and the Ability Academy 3rd Grade is for 13 year olds

oh ok

**Pull request closed without merging**
